services:
  app:
    container_name: twitchy_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./default.env
        required: true
      - path: ./local.env
        required: false
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mongo
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  redis-commander:
    container_name: twitchy_redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "127.0.0.1:8082:8081"
  mongo:
    container_name: twitchy_mongo
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodb:/data/db
  mongoexpress:
    image: mongo-express
    container_name: twitchy_mongo-express
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
