services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./default.env
        required: true
      - path: ./local.env
        required: false
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
  # mongoexpress:
  #   image: mongo-express
  #   container_name: mongo_express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     # ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     # ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  #     ME_CONFIG_BASICAUTH: false
  #   depends_on:
  #     - mongodb
