services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: ./local.env
        required: false
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
