[project]
name = "twitchybackend"
description = "Oya oya"
requires-python = ">=3.12"

[tool.setuptools]
packages = ["twitchybackend"]

[tool.black]
line-length = 79
target-version = ['py312']

[tool.isort]
profile = "black"
line_length = 79
